@SeleniumBaseApi_HostAddress = https://localhost:5000
# run the api so you can run the tests
# don't get near the 1st line nor change its place
# run the tests in order first to make sure that everything is working
# you can try any of them just to see the resluts if you want


# normal Get all request, expected status:[200 OK], expected output:
# [
#   {
#     "id": 1,
#     "url": "https://gitlab.com/users/sign_in",
#     "htmlContent": null,
#     "hasHtmlContent": null
#   }
# ]
GET {{SeleniumBaseApi_HostAddress}}/bypassurl/
Accept: application/json

###

# normal Post request, expected status:[201 Created], expected output:
# {
#   "id": 2,
#   "url": "https://gitlab.com/users/sign_in",
#   "htmlContent": "<test><\test>",
#   "hasHtmlContent": null
# }
POST {{SeleniumBaseApi_HostAddress}}/bypassurl
Content-Type: application/json

{
    "url" : "https://gitlab.com/users/sign_in", 
    "htmlContent" : "<test><\test>"
}

###

# normal Get request, expected status:[200 OK], expected output:
# {
#   "id": 2,
#   "url": "https://gitlab.com/users/sign_in",
#   "htmlContent": "<test><\test>",
#   "hasHtmlContent": null
# }
GET {{SeleniumBaseApi_HostAddress}}/bypassurl/2
Accept: application/json

###

# SeleniumBase Put request, expected status:[204 No Content], expected output: nothing
PUT {{SeleniumBaseApi_HostAddress}}/bypassurl/updateHtml/1
Content-Type: application/json
{
    "id" : 1,
    "url" : "https://gitlab.com/users/sign_in", 
    "htmlContent" : "null"
}

###

# To check on the test above
# expected status:[200 OK], expected output size(too long to put it here): 32368 bytes
GET {{SeleniumBaseApi_HostAddress}}/bypassurl/1
Accept: application/json

###

#norml Put request, expected status:[204 No Content], expected output: nothing
PUT {{SeleniumBaseApi_HostAddress}}/bypassurl/1
Content-Type: application/json
{
    "id": 1,
    "url": "https://gitlab.com/users/sign_in",
    "htmlContent": null,
    "hasHtmlContent": null
}

###